#Conversor de Medidas 
m=float(input('Distância em metros:'))
dm=(m*10)
cm=(m*100)
mm=(m*1000)
km=(m/1000)
hm=(m/100)
dam=(m/10)
print('A distância {}m corresponde a:'.format(m))
print('{}km'.format(km))
print('{}hm'.format(hm))
print('{}dam'.format(dam))
print('{}dm'.format(dm))
print('{}cm'.format(cm))
print('{}mm'.format(mm))